### PR TITLE
[Ko] Fixed Spelling, grammer, etc.

### PR DESCRIPTION
**Pull request by Piggy3590**
# **SCP:SL Translation PR Template**

## **Language Name**
Korean

## **State Type of change (New language, changed existing Etc.)**
spelling, spacing, and removing unnecessary item tutorials (only in korean, so I can't find a reason to put it in)
Also, in the case of MTF, people were dissatisfied with the frequently changed names, so we used the longest remembered name. This fits best with default English.
edited 330, scp items linebreak
11.2 Translated. Communicate with people on South Korea's largest server, most like the Default English.

# **Checklist:**
- [X] I have tested the translation changes ingame
- [ ] I have made sure to not commit changes to multiple translations at the same time, or non-translation repo files
- [x] I have ran `EncodingNormalizer.exe` on my changed files before commiting 
   -  (Exception to this is when edits has __only__ been made in-browser. If this is the case, also check this box.)
- [x] I have made sure that I'm **not** submitting a duplicate translation 
- [X] I have made sure to **not** included any advertisements/pointers to non-game stuff other than the translation author in the credits file
- [X] I have made sure to label my translation folder by [Microsoft Language Tag Standards](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-lcid/a9eac961-e77d-41a6-90a5-ce1a8b0cdb9c)
   - Only in cases of **new** translations (Can be tested [Here](https://rextester.com/WDXPS97501)). Also check this box if the change is **not** a new translation
> For more information regarding game translations, please visit our [README](https://github.com/northwood-studios/SCPSL-Translations/blob/master/README.md) page.

### CODE REVIEW

**Comment by PotatoGoroshi** [comment]
그러면 제가 한 번역도 넣어주실 수 있을까요..?

**Comment by Piggy3590** [comment]
Translated it with the user of the top comment. Added manifest.

**Comment by arti369** [comment]
안녕하세요 혹시 대화 가능하신가요?

**Comment by arti369** [comment]
혼돈의 반란 라이플맨은 그냥 소총수로 하는게 좋을 듯하네요

**Pull request closed without merging**
