### PR TITLE
Finalize the zh-Hans translation, but this time i have something want to talk about

### PR DESCRIPTION
**Pull request by SchrodingerSig**
**please read the comments below**
**please read the comments below**
**please read the comments below**

## Language
zh-Hans

## Type of change
- [x] Added new language translation
- [ ] Changed a currently existing translation

## Have you tested the changes you've made?
- [ ] Yes
- [x] No

# Checklist:
- [x] I have made sure to not commit changes to other stuff than my own or the default english one
- [ ] I have ran `EncodingNormalizer.exe` on my changed files before commiting 
   -  (Exception to this is when edits has __only__ been made in-browser)
- [x] I have made sure that I'm not submitting a duplicate translation 
- [x] I have not included any advertisements/pointers to non-game stuff other than author in the folder name

### CODE REVIEW

**Comment by SchrodingerSig** [comment]
**PLEASE read the whole paragraph / 请阅读全文**
(sorry for letting you guys reading these complex sentences - English is not my first language, so i guess you cant really blame me for that (?)
I really want to solve this in private, but they've been pushing me too hard and i have to do this
since the beginning of this month, Rex and Xiaoyi become extremely active in Chinese SCPSL community, and seems they really want to show players whos the boss. At first they just keep emphasize that "they are studio stuff, and they are the ONLY trustable info resource", then they eliminated (or take over) a fake SCPSL_Official account, which is nice, but there are some details showing that they might used some "extreme" way forcing the fake official account user passing the account to them. and last but not lease, now its about me, and my zh-Hans translation
dont make me wrong, im not panicking for “changing my translations”, im actually appreciate for someone that willing to pointing out my translation errors. the thing that im panicking is the way they treat the translation, like the translation was just a tool for them to secure their position.
in the early days, theyve been keep saying that “Rex is the main translator for zh-Hans”, which i wont deny, since even i made all the translations on Github, as long as MP2 havent been released, Rex will always be the only translator (also because he translated achievements and community news, losing ingame texts wont change the fact that hes the translator) so at that time i didnt really care about that, until 5 days ago, Xiaoyi released some screenshots about the MP2 private build, which includes some Chinese texts in game, and some of them are totally different to the texts i uploaded to Github. Then i quickly realize they have the ability to change the text before put them into the game, so the ingame text will be theirs, and i can hardly prove that the text in game is mine. and the horrible thing is: they are not even trying to hide that, just read the #208 pull request and see how ridiculous these changes are, most of changes are just swapping/deleting a word, and some are just run back to the old texts. they dont care about if the words are correct, they just doing ac much changes as they can, so they can add themself into the credit, proving that they are participated the translation
**So here's my request: Remove ShingekiNoRex (and Tychus_Xiaoyi) from this project, or make 2 version of zh-Hans, so I can keep the proper translation (least it wont be used for improper usage), and they can still do their shit with their version.**
Schrodinger_Sig

**Comment by SchrodingerSig** [comment]
(from now its in Chinese)
我真的不打算把这件事放到台面上来说，但是他们真的已经把我逼上绝境了。
自从这个月初Rex和骁奕正式开始在国内SCPSL社区活跃开始，他们一直在进行着所谓“宣示主权”的行为，先是从一开始强调“自己是官方人员，只有他们的消息是可靠的”，再是取缔假官方B站账号（虽然假官方肯定是违法的，但是整件事所透露出的细节来看，他们在取缔过程中绝对拿不上台面），到最后涉及到我，确切来说是我的翻译文本。
别误会，我并不是想表达我的文本有多好，毕竟我巴不得一群人在那边指我的文本有那些问题。真正让我感到不寒而栗的是他们在将汉化文本单纯当作“工具”，能够让他们能在脸上贴金的工具在使用。
早前Rex和骁奕就在强调，Rex是这游戏的翻译。起先我并未在意，毕竟就算在Github上的文本几乎全是我的，但我也只有在MP2实装我的文本之后，才够格称自己为SCPSL的翻译，更何况Rex的确有进行其他方面的翻译（比如成就，社区新闻（？）但在五天前，骁奕发布了几张MP2测试服的截图，其中的中文文本和我的文本有部分出入。这算是第一次我对我的文本感觉出危机感，毕竟他们完全可以在私底下把文本大幅修改一下，这样汉化就成出自他们之手，我也难以证明游戏内的文本就是我在Github上上传的文本。而事实比这更加过分，他们甚至都不打算掩盖这件事，直接发起了Pull Request，除了部分为了改动而改动的文本，还有部分文本被还原成了旧翻译（先不说内容是对是错，老文本是Rex翻的，这种行为相当于是在减少新文本的出现，让玩家误以为Rex是基于现有文本添加新内容）初次之外，在言语中也能发现对我的不屑，“助手■某人”这个称呼就是个很好的例子。我原以为被蚕食的只有作为劳动力的我，但事实上真正被蚕食的是我的文本，我甚至还不如被蚕食的份。
**所以我在这里郑重请求：将ShingekiNoRex（和Tychus骁奕）移出此项目，或是将简中文本分裂出两个版本，这样我相对正式的文本能得以保留（至少不会被用作其他不正当行径），而他们也能对另外的版本想咋样就咋样，原地自嗨。**
以上。
薛定谔的西格

**Comment by ShingekiNoRex** [comment]
1.关于B站虚假账号一事，我在管理层授权下向B站官方提交了请求和证明但遭到驳回。之后骁奕刚加入工作室就独断专行找账号拥有者以不正当的方式解决了此事，其言行我也无法认可。
2.我从未强调过我是游戏的唯一翻译，因为我的本职是程序员，我无法在翻译上花费过多的精力，我欢迎所有玩家都能提供帮助，我所作的工作仅仅是最后的整合、校对和润色。
3.我们在内测阶段使用的文本是自动从Github上抓取的最新主分支，但是有时候文本可能不会自动更新至最新版。我从未擅自修改过任何文本。
4.在几个月前我收到了TitanSix关于原本我翻译的文本的抱怨，我也拜托了他对此进行修改。之后也委托了骁奕对你翻译的文本进行润色。今天提交的PR是我在仔细核对了三人的翻译内容后作出的修改，并且修正了一些错误。
5.除了B站和Steam，我从未在任何中文社区有过活跃行为，也从未对你表达过任何轻蔑，不清楚你所说的“助手■某人”是什么意思。

**Comment by ShingekiNoRex** [comment]
另外，如果需要的话，我提交的PR中包含的每处修改都可以给出我选择这种翻译的理由

**Comment by X-EROS** [comment]
中國人不打中國人，就現況解決方法應該是要简中分家了，但明顯官方一定不同意，你們還是和好吧。
多人的翻译就需要協調，你們就應該有一個群組來溝通，在選字才可以有共識。
但有一樣東西我不明白，一開始官方的簡中跟繁中是一樣，我不知道是不是你們直接繁變簡，因為我在做繁中有時候會有口語問題，看到你們简中也有，反正我沒在意，因為原本官方出中文的時候我就有意想把繁簡也拿來做，而且官方當初出中文直接叫Chinese，也沒有分別簡中繁中，後來還是算了。

**Comment by ShingekiNoRex** [comment]
> 但有一樣東西我不明白，一開始官方的簡中跟繁中是一樣，我不知道是不是你們直接繁變簡，因為我在做繁中有時候會有口語問題，看到你們简中也有，反正我沒在意，因為原本官方出中文的時候我就有意想把繁簡也拿來做，而且官方當初出中文直接叫Chinese，也沒有分別簡中繁中，後來還是算了。

我只做了简中的，应该是有人直接把简中转换成了繁中。

**Comment by X-EROS** [comment]
> > 但有一樣東西我不明白，一開始官方的簡中跟繁中是一樣，我不知道是不是你們直接繁變簡，因為我在做繁中有時候會有口語問題，看到你們简中也有，反正我沒在意，因為原本官方出中文的時候我就有意想把繁簡也拿來做，而且官方當初出中文直接叫Chinese，也沒有分別簡中繁中，後來還是算了。
> 
> 我只做了简中的，应该是有人直接把简中转换成了繁中。

你是不是搞錯繁中跟简中，你那句話應該是這樣說"应该是有人直接把繁中转换成了简中"。

**Comment by ShingekiNoRex** [comment]
> 你是不是搞錯繁中跟简中，你那句話應該是這樣說"应该是有人直接把繁中转换成了简中"。
记不清了，当时管理比较松散，好像确实简中的版本曾被替换成了直接简化的繁中

**Comment by SchrodingerSig** [comment]
> 1.关于B站虚假账号一事，我在管理层授权下向B站官方提交了请求和证明但遭到驳回。之后骁奕刚加入工作室就独断专行找账号拥有者以不正当的方式解决了此事，其言行我也无法认可。
> 2.我从未强调过我是游戏的唯一翻译，因为我的本职是程序员，我无法在翻译上花费过多的精力，我欢迎所有玩家都能提供帮助，我所作的工作仅仅是最后的整合、校对和润色。
> 3.我们在内测阶段使用的文本是自动从Github上抓取的最新主分支，但是有时候文本可能不会自动更新至最新版。我从未擅自修改过任何文本。
> 4.在几个月前我收到了TitanSix关于原本我翻译的文本的抱怨，我也拜托了他对此进行修改。之后也委托了骁奕对你翻译的文本进行润色。今天提交的PR是我在仔细核对了三人的翻译内容后作出的修改，并且修正了一些错误。
> 5.除了B站和Steam，我从未在任何中文社区有过活跃行为，也从未对你表达过任何轻蔑，不清楚你所说的“助手■某人”是什么意思。

2.我没说你是“唯一翻译”，你也的确没强调你是*唯一翻译*，你只不过是先强调你是工作室成员，说自己是唯一可靠消息来源，然后再顺带提一嘴自己是翻译（仔细倒一倒这个逻辑，本质上两者没太大区别）
3.我没记错的话，SCPSL_Official目前是骁奕在管理是吧？https://t.bilibili.com/324996889643301807?tab=2 这是在#208 Pull Request之前他发的游戏内截图。放在之前那个时间点，我能不能认为是有人打算拿我的文本在私底下进行修改再实装？
4.也就是说润色=改一两个字+把部分文本替换回老文本？www.bilibili.com/video/av77135611
5.这条和3.一样，和骁奕(SCPSL_Official)有关https://t.bilibili.com/325750196838580352?tab=2 上面的内容是冲着你们两人的，不是说你就是说骁奕 >:)

**Comment by SchrodingerSig** [comment]
分不分裂简中文本先暂时放一放，先把MP2的简中内容确定下来。
我会在太平洋时间10点（三个小时后）直播最后过一次文本
顺带解答下部分文本我的翻译思路
如果你们真打算以方便国内玩家为主的话，欢迎加入讨论

**Comment by SchrodingerSig** [comment]
https://www.twitch.tv/schrodinger_sig
开工

**Comment by SchrodingerSig** [comment]
播完了，频道链接删了（以免有人觉得我打广告啥的）
没人来看
嘤嘤嘤

**Comment by Rnen** [comment]
# Management Response

> "So here's my request: Remove ShingekiNoRex (and Tychus_Xiaoyi) from this project, or make 2 version of zh-Hans, so I can keep the proper translation (least it wont be used for improper usage), and they can still do their shit with their version."

This request cannot be fulfilled. Both Shigenki & Xiaoyi has done work on the translation, which deserves to be credited. As long as they have contributed with something productive to the translation, they are free to add themselves to the credits like any other person. Although this does not mean that they are allowed to change the order of credits, so you as a initial creator/contributor will always be the first name on the list.

> "Change a word or two + replace part of the text back to the old text?"

Our translation maintainers have done substantially more work than what you are suggesting. Also, if the old version turns out to be more correct in some form, they are free to handle that situation respectively at their own terms.
For future discussions, i urge you to be less agressive in tone, as sarcasm usually leads to no good. Although i do understand that some sentences gives the wrong tone, due to translation. I myself have english as a second language.

> "Xiaoyi released some screenshots about the MP2 private build, which includes some Chinese texts in game, and some of them are totally different to the texts i uploaded to Github."

Like Shigenki earlier pointed out, our automatic system for putting the translations into the game has recently been faulty, nobody has stolen your translation. The pictures you have posted, is most likely not from a updated version of the language, something we will resolve shortly. Please do also note that users are free to alter their translations locally as they please, hence screenshots from another user may not be displaying the translations the same way as they are on the repo.

---
As for your request about creating a second translation, there will only be one of each language.
If you believe that your language (or the opposing translation) is different from standard `zh-Hans`:  
image

Then i urge you to check out the [Microsoft Language Tag Documentation](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-lcid/a9eac961-e77d-41a6-90a5-ce1a8b0cdb9c) which contains a full list of chinese language tags. Please note that **only** "Release A" versions are viable.

> "Rex and Xiaoyi become extremely active in Chinese SCPSL community, and seems they really want to show players whos the boss. At first they just keep emphasize that "they are studio stuff, and they are the ONLY trustable info resource ", then they eliminated (or take over) a fake SCPSL_Official account, which is nice, but there are some details showing that they might used some" extreme "way forcing the fake official account user passing the account to them."

This is not related to this translation repo in any way. Please do not include offtopic issues in any future PRs.

**Comment by Rnen** [comment]
Your approved changes has been included in another PR due to time constraints.
We hope you are satisfied with the new changes, and urge you to continue this colaboration.
Thank you for your time :slightly_smiling_face:

**Comment by SchrodingerSig** [comment]
> # Management Response
> > "So here's my request: Remove ShingekiNoRex (and Tychus_Xiaoyi) from this project, or make 2 version of zh-Hans, so I can keep the proper translation (least it wont be used for improper usage), and they can still do their shit with their version."
> 
> This request cannot be fulfilled. Both Shigenki & Xiaoyi has done work on the translation, which deserves to be credited. As long as they have contributed with something productive to the translation, they are free to add themselves to the credits like any other person. Although this does not mean that they are allowed to change the order of credits, so you as a initial creator/contributor will always be the first name on the list.
> 
> > "Change a word or two + replace part of the text back to the old text?"
> 
> Our translation maintainers have done substantially more work than what you are suggesting. Also, if the old version turns out to be more correct in some form, they are free to handle that situation respectively at their own terms.
> For future discussions, i urge you to be less agressive in tone, as sarcasm usually leads to no good. Although i do understand that some sentences gives the wrong tone, due to translation. I myself have english as a second language.
> 
> > "Xiaoyi released some screenshots about the MP2 private build, which includes some Chinese texts in game, and some of them are totally different to the texts i uploaded to Github."
> 
> Like Shigenki earlier pointed out, our automatic system for putting the translations into the game has recently been faulty, nobody has stolen your translation. The pictures you have posted, is most likely not from a updated version of the language, something we will resolve shortly. Please do also note that users are free to alter their translations locally as they please, hence screenshots from another user may not be displaying the translations the same way as they are on the repo.
> 
> As for your request about creating a second translation, there will only be one of each language.
> If you believe that your language (or the opposing translation) is different from standard `zh-Hans`:
> image
> 
> Then i urge you to check out the [Microsoft Language Tag Documentation](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-lcid/a9eac961-e77d-41a6-90a5-ce1a8b0cdb9c) which contains a full list of chinese language tags. Please note that **only** "Windows 7" version or less are viable.
> 
> > "Rex and Xiaoyi become extremely active in Chinese SCPSL community, and seems they really want to show players whos the boss. At first they just keep emphasize that "they are studio stuff, and they are the ONLY trustable info resource ", then they eliminated (or take over) a fake SCPSL_Official account, which is nice, but there are some details showing that they might used some" extreme "way forcing the fake official account user passing the account to them."
> 
> This is not related to this translation repo in any way. Please do not include offtopic issues in any future PRs.

Thanks for the reply, although i dont think close this Pull Request without actually solving this problem is kind impolite
the main reason im pissed off is: 
1, most of line only changed one or two words (not one or two lines for different lines, but literally *one or two words for all this type of changes*), it didnt change anything, like the overall meaning, grammar or something, but still being consider as changes. 
2, some of their changes are wrong/improper, like Unarmed, Sinkhole, MenuWarning.txt line 2, 
I made 2 videos about this, one is talking about they being impolite to me and changing the line in secret (*the changes are exactly same as #208 Pull Request, but that video was made before #208), and the other just analyze the #208 Pull Request and pointing out all the problems. if you want. im willing to make another video in English, explaining why this change is unproper, and other stuff
also, even though im appreciate for your reply, im more expecting Rex facing me and answering my questions, and figure out a way to contact with other "translators" so we can talk about the #208 PR further
(btw there are some new changes which not been included in #208 PR, ill start another PR just for adding these lines (and fix the miss-translation) )

**Comment by SchrodingerSig** [comment]
reply in Chinese, with more explanations
感谢回复，虽说在事情尚未解决的情况下关闭这个Pull Request有点不礼貌
我再次重申真正令我生气的两点：
1、大部分修改支队一两个单字进行了修改（字面上的“一两个单字”，比如说“将”，这些基本上都是个人翻译风格用词，不同人翻同一句话肯定都会有用词不同，对这些词针对性修改，我有理由相信这是含有恶意的）这类修改不会改变整体意思，语法之类的，但是依旧算作“进行了修改”（这点是我把这次修改定性为恶意行为的主要原因，因为只是进行这些无意义的修改，他们就有理由将自己加入翻译名单）
2、有相当一部分的改动是错翻，比如说
Unarmed（无武装→手无寸铁，人类的四个被动Unarmed, Access Card, Standard Issue, Armed & Dangerous 指的是武装等级，手无寸铁无法用来形容武装程度）
Sinkhole（区块腐蚀→沉洞，当前版本(MP1)对Sinkhole一共有三种叫法，我这里在统一了Sinkhole为“次元洞”，由于这个词作为能力有点不合适，所以我挑了个中二的“区块腐蚀”(我承认这点是我自己改的) 就算维持原文翻译，也应该使用MP1中的另一种叫法“渗穴”）
MenuWarning.txt 的第二条（整个句意都变了谢谢）
WeaponManager.txt （目前版本的武器控制面板只用于丢弃弹药而不是改装武器(武器站)，我所以把右方向键描述改成了弹药，然后他们给我回去了可还行）
我已经就这件事做了两个视频，一个(av77116191)是针对他们的无礼行为（核心原因）和私底下修改文本（冲突之一）做阐述（视频制作时略早于#208PR），另一个(av77135611)是就#208PR的修改进行评价（虽说是消极方面）如果有需要，我愿意将上述内容重新整合，制作英文版本并上传至Youtube
最后，虽然我很感谢有权限更高的人员对我进行回复，但我更希望Rex能就我上面（包括后续补充）的问题进行正面回复，并想办法将几个“翻译”面对面，就#208的改动进行讨论
（顺带，我这个PR的部分改动是在#208之后再行修改的，所以我稍后会再开一个PR重新进行这些改动（顺带把上面提到的几个错翻改了）

**Comment by SchrodingerSig** [comment]
@Rnen @ShingekiNoRex

**Comment by SchrodingerSig** [comment]
*注：添加新语言(仅)会作为我最后维护我的文本的手段，刻意改变翻译整体风格已经属于大幅度改动文本了

**Comment by SchrodingerSig** [comment]
ive changed all of the mistranslations in #242, with explaination
i leaved all the lines that only changed 1 or 2 words there, since thats basically most of the changes from #208. changing these back are basically back to #209 
i still want to remind you guys: that is the cheapest way to get into credit without doing any specific work
shame on you guys
(im still waiting for Rex's reply)

**Comment by ShingekiNoRex** [comment]
I'm writing this in english so that my colleagues can read it without translator.
First we would like to suggest you the nature of Github. It's a collaborative process, overseen by official staff. You are the contributor, not the owner of the translation. Everyone can contribute to it without your permission. Essentially, any person that contributes any amount of work is a contributor and can be sourced/cited/credited. This is their right, and is covered under intellectual property. They did work, and receive credit. This is common practice within the field of localization, writing, translating, even in China.
It's our duty to check whether these changes are productive, and decide which one is better. You are welcome to suggest anything politely, but it will be us to make the final decision.
Speaking of your latest pull request, we have viewed it, and thanks to you, found a mistake in our translation, which will be corrected later. But most of your changes are not appropriate from our view. And some of these functions are implemented by myself. I know how to translate it in a more accurate way.
If you still insist on your own opinion, we have to end up locking the discussion, as it will be a waste of time. Most of we maintainers have other works on the game to do, and we can't afford spending more on such a drama and getting the schedule of MP2 delayed.

**Comment by SchrodingerSig** [comment]
welp if you are gonna keep avoiding the question, i dont mind to wast more time on you and your crew
1, i know anyone can change the translations on github, and im appreshate for the changes that are legit (if you do watched my second vid and my stream, youll see im good with some of the changes) what about the changes that *only swap one word into anoher word*? thats the main reason im pissed off and you are not gonna answer that right?
(Chinese gramma is kind different to English, changing/deleting modal wont change the whole sentence)
(heres some similar changes in English, and just image you write a book, and someone did any of these changes and want add his name into "author", will that be legit?)
(Hi → Hello) (friend → mate) (bye → see ya) (great → awesome) (okay → alright)
2, the reason im here and helping translate MP2 content is bacause the current translation in game (which was made by **you**) contain tons of ranslation error, or logic mistakes (its not personal attack, because it is the truth)
(i hope you didnt forget "被瘟疫治愈了"(been cured by plage) bacause i used that one as a example on my SCPSL community disscusstion) 
you already admit your translations are improper, then why would you claim your changes are legit this time? some of the changes are leterally change back to the current version(MP1). you can totally ignore my community disscusstion if your translation if totally fine, but you didnt. 
i guess you really want someone doing everything for you, so you can sitting back and waiting to add you and your friend into the credit ;)
3, you are keep avoiding answer the question, treating me with "locking the discussion", "delay MP2", and now you want me to be polite? if you are not being polite to me, why would i do? i already said my suggestion, on my second vid, guess you just really dont want to care about this or did ya
4, to define if a translation is good or not, its not depend on you, but the player. im taking the zh-CN, and lets see what will happen

**Comment by Rnen** [comment]
I'm locking this, as this discussion does not need to take place here.
If you still want to discuss this, then open a issue on the GitHub, or contact us via mail.
I realize the word "author" has an unintended effect upon the credits file, and it has been removed.
Now the credits file only contain "contributors", as translations submitted through GitHub is Studio Property. Sorry for the confusion.

**Pull request closed without merging**
