### PR TITLE
Changes to "Danish Translations" Removed all "?"

### PR DESCRIPTION
**Pull request by Bemsen**
# SCP:SL Translation PR Template

## Language
(Replace this text with language name)

## Type of change
- [ ] Added new language translation
- [x] Changed a currently existing translation

## Have you tested the changes you've made?
- [ ] Yes
- [x] No

# Checklist:
- [x] I have made sure to not commit changes to other stuff than my own or the default english one
- [ ] I have ran `EncodingNormalizer.exe` on my changed files before commiting 
   -  (Exception to this is when edits has __only__ been made in-browser)
- [x] I have made sure that I'm not submitting a duplicate translation 
- [ ] I have not included any advertisements/pointers to non-game stuff other than author in the folder name

### CODE REVIEW

**Comment by Bemsen** [comment]
Which folder? I'm having trouble navigating this thing.


Den søn. 7. apr. 2019 kl. 00.46 skrev Evan <notifications@github.com>:

**Comment by Rnen** [comment]
That would be the main folder containing the .txt files :slightly_smiling_face: 

image

**Comment by Bemsen** [comment]
I don't really get what you mean, since there's a lot of things I have to navigate through. Could it be possible if you contacted me on discord, or something?

**Comment by Bemsen** [comment]
I don't really know how to do it.

**Comment by Rnen** [comment]
Thats ok, GitHub can be confusing :smile:

**Comment by Bemsen** [comment]
Wait, I forgot some missing lines in SCP079.txt

How can I change them?

It was these
You are being attacked!
Generators have been highlighted on the map
DANGER
SCPs{0}MTF & Guards{1}Scientists{2}Class-D{3}Chaos Insurgents{4}

And I wanted to translate them into
Du er under angreb!
Generatorer er blevet markeret på kortet
ADVARSEL
SCPs{0}MTF & Sikkerhedvagter{1}Videnskabsmænd{2}Klasse-D{3}Kaos Oprører{4}

**Comment by Rnen** [comment]
Just edit them in your browser-editor :slightly_smiling_face:

**Comment by Bemsen** [comment]
It would be nice, if you could fix it for me!
I don't want to screw it up again lol

**Comment by Rnen** [comment]
Done :ok_hand:

**Comment by Rnen** [comment]
@Bemsen Right now, i added some new translation files to the english folder
[As can be seen here](https://github.com/northwood-studios/SCPSL-Translations/commit/75a55bf1865b84bc3d80ca26d3264b3cbed34d1e)

Tought i'd let you know just in case you wished to update the Danish to include theese.
I do not require any response to this. If you do wish to add the new files, create a new Merge Request :smile:

**Pull request merged**
