### PR TITLE
TC New Update (13/10)

### PR DESCRIPTION
**Pull request by X-EROS**
# SCP:SL Translation PR Template

## Language Name
(Input the changed Language's name here)

## State Type of change (New language, changed existing Etc.)
(My Change descrtiption here)

# Checklist:
- [x] I have tested the translation changes ingame
- [x] I have made sure to not commit changes to multiple translations at the same time, or non-translation repo files
- [x] I have ran `EncodingNormalizer.exe` on my changed files before commiting 
   -  (Exception to this is when edits has __only__ been made in-browser. If this is the case, also check this box.)
- [x] I have made sure that I'm **not** submitting a duplicate translation 
- [x] I have made sure to **not** included any advertisements/pointers to non-game stuff other than the translation author in the credits file
- [ ] I have made sure to label my translation folder by [Microsoft Language Tag Standards](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-lcid/a9eac961-e77d-41a6-90a5-ce1a8b0cdb9c)
   - Only in cases of **new** translations (Can be tested [Here](https://rextester.com/WDXPS97501)). Also check this box if the change is **not** a new translation

### CODE REVIEW

**Comment by Tychus-Xiaoyi** [comment]
感謝您的及時翻譯，我對您的文本進行了一個潤色修改(文本對齊和增大文本間隔)用於提高遊戲內觀感和實際操作體驗，以及一個錯誤修改。請您檢查修改後的文本，如果無異議請在本周內回復我。感謝您對SCP:SL的支持!

**Comment by X-EROS** [comment]
為什麼是請在旁等候，而不是請等候?

**Comment by X-EROS** [comment]
除了請在旁等候，沒有其他問題了

**Comment by Tychus-Xiaoyi** [comment]
> 除了請在旁等候，沒有其他問題了

原文為“PLEASE STAND BY”且結合遊戲中需要站在工作站旁才能正常顯示和使用工作站。

**Review by Tychus-Xiaoyi — APPROVED** [review]

**Pull request merged**
