### PR TITLE
Italian Translation Rework (Reworked Workstations.txt, NewMainMenu.txt, DecontaminationDisplays.txt)

### PR DESCRIPTION
**Pull request by Bay62**
# SCP:SL Translation PR Template

## Language Name
Italian

## State Type of change (New language, changed existing Etc.)
changed existing

# Checklist:
- [x] I have tested the translation changes ingame
- [x] I have made sure to not commit changes to multiple translations at the same time, or non-translation repo files
- [x] I have ran `EncodingNormalizer.exe` on my changed files before commiting 
   -  (Exception to this is when edits has __only__ been made in-browser. If this is the case, also check this box.)
- [x] I have made sure that I'm **not** submitting a duplicate translation 
- [x] I have made sure to **not** included any advertisements/pointers to non-game stuff other than the translation author in the credits file
- [x] I have made sure to label my translation folder by [Microsoft Language Tag Standards](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-lcid/a9eac961-e77d-41a6-90a5-ce1a8b0cdb9c)
   - Only in cases of **new** translations (Can be tested [Here](https://rextester.com/WDXPS97501)). Also check this box if the change is **not** a new translation
> For more information regarding game translations, please visit our [README](https://github.com/northwood-studios/SCPSL-Translations/blob/master/README.md) page.

### CODE REVIEW

**Review by Rnen — CHANGES_REQUESTED** [review]
Please don't add things such as Size changes where the english doesn't use it.
Also, if you think this translation _needs_ it, include pictures of before & after with a detailed reason why.

**Comment by Bay62** [comment]
Tonight I will send the screens however I put the size because the translations come out of the Decontamination screens and it is not possible to click on the workbench, only where the writings are recorded, after I will make them understand better

**Comment by Bay62** [comment]
https://user-images.githubusercontent.com/56767731/116462568-df850000-a869-11eb-8063-bf1eea001516.mp4

SCP Secret Laboratory 2021 04 28 - 21 32 15 01

image

image

For now these are the images of SCP:SL Translation ITA, tomorrow or after I'll send you later Translation with <size> but if you look at the workstation video (I hit E on write "ESTENZIONI DELLA CANNA, barrel extensions," but nothing happened) I had to go to the center where nothing was written @Rnen

**Comment by Bay62** [comment]
> Please don't add things such as Size changes where the english doesn't use it.
> Also, if you think this translation _needs_ it, include pictures of before & after with a detailed reason why.

    https://youtu.be/GQ0_uTuBYbk


@Rnen

**Review by Rnen — APPROVED** [review]

**Comment by Rnen** [comment]
Thanks! Apologies for the delay, It's been a hectic month.

**Pull request merged**
