### PR TITLE
[pt-BR] Improved Brazilian-Portuguese Translation

### PR DESCRIPTION
**Pull request by Firething**
# **SCP:SL Translation PR Template**

## **Language Name**
Brazilian Portuguese (PT-BR)

## **State Type of change (New language, changed existing Etc.)**
Updated Abilities, AttachmentEditors, AttachmentNames, AttachmentParameters, Badges, Categories, Class_Bio, Class_Descriptions, Class_NickNames, Connection_Errors, Connection_Info, DeathReasons, DecontaminationDisplays, Facility, Items, KeyBinds, Legacy_Interfaces, LoadingHints, MainMenu, MenuWarnings, NewMainMenu, Nuke_Silo_Sign, SCP079, SCP330, Subtitles and Summary. All mentioned had lots of grammar problems, words that didn't match the real translation and non-updated descriptions [PARABELLUM, scp-079 having 5 generators for example], so I just fixed them. Also made it easier to understand!

# **Checklist:**
- [X] I have tested the translation changes ingame
- [X] I have made sure to not commit changes to multiple translations at the same time, or non-translation repo files
- [X] I have ran `EncodingNormalizer.exe` on my changed files before commiting 
   -  *( Exception to this is when edits has __only__ been made in-browser. If this is the case, also* ***check this box*** *)*
- [X] I have made sure that I'm **not** submitting a duplicate translation 
- [X] I have made sure my addition follows guidelines described in the [CONTRIBUTING.md](https://github.com/northwood-studios/SCPSL-Translations/blob/master/.github/CONTRIBUTING.md) file
- [X] I have made sure to label my translation folder by [Microsoft Language Tag Standards](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-lcid/a9eac961-e77d-41a6-90a5-ce1a8b0cdb9c)
   - Only in cases of **new** translations (Can be tested [Here](https://rextester.com/WDXPS97501)). Also check this box if the change is **not** a new translation

### CODE REVIEW

**Comment by MichalPetryka** [comment]
You should probably coordinate the changes with @FerarOFoda since they recently updated the brazilian translation.

**Comment by FerarOFoda** [comment]
> You should probably coordinate the changes with @FerarOFoda since they recently updated the brazilian translation.

It's all OK!

**Comment by Firething** [comment]
TranslationManifestChecker won't work after updating manifest.json   
translation

**Comment by FerarOFoda** [comment]
> TranslationManifestChecker won't work after updating manifest.json   
> translation
> 

@MichalPetryka do you think you could fix this?

**Review by FerarOFoda — COMMENTED** [review]
We(me and firething) agreed this is the perfect final result.
But It's almost been a week since the Manifest.json has problems we don't know how to solve

**Comment by FerarOFoda** [comment]
@Rnen When I posted my pull request you managed to solve this TranslationManifestChecker issue, do you think you could do that again for this one? Its alredy been half a month

**Comment by Rnen** [comment]
> @Rnen do you think you could do that again for this one?

<h3>Yeah sure, I'll take a look either at the end of the week or on Monday 👍 </h3>
To be fair it is an easy fix if you know where to look, and have the files locally on your computer 😄
<details>
<summary>Heres a small guide if you're interested</summary>

image
1. Copy the line from above
2. Edit the path to be correct
3. Use CMD or your preferred method to run that command. (either start CMD in the root repo folder or navigate to it)
</details>

**Comment by Firething** [comment]
Got it fixed, waiting for the review now 👏

**Review by Rnen — APPROVED** [review]
Thanks 👍

**Pull request merged**
