### PR TITLE
Brazilian Portuguese Translation Overhauls

### PR DESCRIPTION
**Pull request by FerarOFoda**
# **SCP:SL Translation PR Template**

## **Language Name**
pt-BR Brazillian Portuguese

## **State Type of change (New language, changed existing Etc.)**
Updated Summary to new format, Subtitles, Loading hints, SCP-330 candies descriptions, fixed clipping in Decontamination text, added Death Reasons, added Attatchment Descritive Upgrades, Downsides, Editors. Added Disarming text and general improvements in previously translated files

# **Checklist:**
- [x] I have tested the translation changes ingame
- [x] I have made sure to not commit changes to multiple translations at the same time, or non-translation repo files
- [x] I have ran `EncodingNormalizer.exe` on my changed files before commiting 
   -  *( Exception to this is when edits has __only__ been made in-browser. If this is the case, also* ***check this box*** *)*
- [x] I have made sure that I'm **not** submitting a duplicate translation 
- [x] I have made sure my addition follows guidelines described in the [CONTRIBUTING.md](https://github.com/northwood-studios/SCPSL-Translations/blob/master/.github/CONTRIBUTING.md) file
- [x] I have made sure to label my translation folder by [Microsoft Language Tag Standards](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-lcid/a9eac961-e77d-41a6-90a5-ce1a8b0cdb9c)
   - Only in cases of **new** translations (Can be tested [Here](https://rextester.com/WDXPS97501)). Also check this box if the change is **not** a new translation
> For more information regarding game translations, please visit our [README](https://github.com/northwood-studios/SCPSL-Translations/blob/master/README.md) page.

### CODE REVIEW

**Comment by FerarOFoda** [comment]
I can't see the issue here, if its the fact some files dont exist its because there are files that are needed in the brazillian translation so I added them
image

**Comment by FerarOFoda** [comment]
Tested all additional translations in-game, I am 100% sure it's ready.

**Comment by Dr-Ham** [comment]
Are you sure? According to the translations checker, there are still some missing translations (lines)

**Comment by FerarOFoda** [comment]
> Are you sure? According to the translations checker, there are still some missing translations (lines). eg there are 6 item translations missing

I'm going through every translation file to see whats wrong

**Comment by FerarOFoda** [comment]
Ok, I solved all missing lines

**Comment by MichalPetryka** [comment]
You can add yourself to authors in `manifest.json` if you want to be included in the credits.

**Comment by FerarOFoda** [comment]
> You can add yourself to authors in `manifest.json` if you want to be included in the credits.

Ok thank you

**Comment by FerarOFoda** [comment]
So how do I run a translationmanagernomalizer.exe considering this was edited through web

**Review by FerarOFoda — COMMENTED** [review]
.

**Comment by Dr-Ham** [comment]
How different are brazilian pt and portugal pt? The “normal” pt translation hasn’t been updated in 3 years either, and for sure it’s not good. 
Perhaps they could be merged, if they aren’t very different?

**Comment by FerarOFoda** [comment]
there are many differences it wouldnt make much sence to merge them, but maybe (just maybe I could get help from my friends from portugal to make an pt translation), for an example the word used for "woman" there means "sl*t" in here

**Comment by FerarOFoda** [comment]
> How different are brazilian pt and portugal pt? The “normal” pt translation hasn’t been updated in 3 years either, and for sure it’s not good. 
> Perhaps they could be merged, if they aren’t very different?

there are many differences it wouldnt make much sence to merge them, but maybe (just maybe I could get help from my friends from portugal to make an pt translation), for an example the word used for "woman" there means "sl*t" in here

**Comment by FerarOFoda** [comment]
Made a last review of the translation just for precaution, I thinks its everything alright so I'll only be making changes requested by the review (Unless yall ask for anything before it)

**Review by Rnen — APPROVED** [review]
Thanks :grin: We really needed an update for this, so much appreciated!

**Pull request merged**
