### PR TITLE
Added Serbian (Cyrillic)

### PR DESCRIPTION
**Pull request by LazarOroz**
# **SCP:SL Translation PR Template**

## **Language Name**
Serbian (Cyrillic)

## **State Type of change (New language, changed existing Etc.)**
New Language

# **Checklist:**
- [X] I have tested the translation changes ingame
- [X] I have made sure to not commit changes to multiple translations at the same time, or non-translation repo files
- [X] I have ran `EncodingNormalizer.exe` on my changed files before commiting 
   -  *( Exception to this is when edits has __only__ been made in-browser. If this is the case, also* ***check this box*** *)*
- [X] I have made sure that I'm **not** submitting a duplicate translation 
- [X] I have made sure my addition follows guidelines described in the [CONTRIBUTING.md](https://github.com/northwood-studios/SCPSL-Translations/blob/master/.github/CONTRIBUTING.md) file
- [X] I have made sure to label my translation folder by [Microsoft Language Tag Standards](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-lcid/a9eac961-e77d-41a6-90a5-ce1a8b0cdb9c)
   - Only in cases of **new** translations (Can be tested [Here](https://rextester.com/WDXPS97501)). Also check this box if the change is **not** a new translation
> For more information regarding game translations, please visit our [README](https://github.com/northwood-studios/SCPSL-Translations/blob/master/README.md) page.

### CODE REVIEW

**Comment by Rnen** [comment]
image
Please note that Steam doesn't support Serbian as a localization, so the `.vdf` files will sadly not be used.

**Comment by LazarOroz** [comment]
I understand, I have looked through the list and saw it though, although as far as I know they will support it soon.

**Comment by Rnen** [comment]
> I understand, I have looked through the list and saw it though, although as far as I know they will support it soon. My apologies for any complications. Maybe I looked in another section and not "Full Platform Support". Will the language be added or do I need to do some changes?

No changes needed about this specific matter, will have to check the integrity of the PR later when I'm off work. 😄

**Comment by Rnen** [comment]
> (Also what does PR mean?)

Pull Request. AKA this very page 😁
 
image

As the picture shows, this is PR #1099 (don't worry, it's also counting closed ones, so there's not a huge queue in front of you)3




> Also in the forums you said I could get a discord role to talk to other translators, can I get that please if I need help with some strings because the response I am guessing would be faster there.

Just @ me or someone else from the translation team in the discord in some other channel and we'll have it sorted out. If you have trouble finding me, here: 
image

**Review by Rnen — APPROVED** [review]

**Comment by LazarOroz** [comment]
Alright, I'll go do that later. Thank you!!

**Pull request merged**
