### PR TITLE
Ukrainian update for latest changes

### PR DESCRIPTION
**Pull request by Rayfulrand**
# SCP:SL Translation PR Template

## Language Name
Ukrainian

## State Type of change (New language, changed existing Etc.)
Updating translations to fit current Master version, several strings are changed for better readness

# Checklist:
- [x] I have tested the translation changes ingame
- [x] I have made sure to not commit changes to multiple translations at the same time, or non-translation repo files
- [x] I have ran `EncodingNormalizer.exe` on my changed files before commiting 
   -  (Exception to this is when edits has __only__ been made in-browser. If this is the case, also check this box.)
- [x] I have made sure that I'm **not** submitting a duplicate translation 
- [x] I have made sure to **not** included any advertisements/pointers to non-game stuff other than the translation author in the credits file
- [x] I have made sure to label my translation folder by [Microsoft Language Tag Standards](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-lcid/a9eac961-e77d-41a6-90a5-ce1a8b0cdb9c)
   - Only in cases of **new** translations (Can be tested [Here](https://rextester.com/WDXPS97501)). Also check this box if the change is **not** a new translation

### CODE REVIEW

**Review by GuyFawkes76 — DISMISSED** [review]

**Review by Rayfulrand — COMMENTED** [review]
Changes are made to align translations with current English version. Several grammar typos fixed

**Comment by Rayfulrand** [comment]
Hm, It seems I made a mistake by deleting all other folders from my branch

**Comment by OneKoin** [comment]
You should not erase files as everything you did will be merged when your pull request is approved.

Close this pull request, delete your repo and fork this repo again.

**Comment by Dat-Joseph** [comment]
> You should not erase files as everything you did will be merged when your pull request is approved.
> 
> Close this pull request, delete your repo and fork this repo again.

As OneKoin said, please do that. Reopen another pullrequest, but that time with the other translations being **not** deleted :P

**Pull request closed without merging**
