### PR TITLE
Updated Russian localization

### PR DESCRIPTION
**Pull request by realmbmc**
# SCP:SL Translation PR Template

## Language
Russian

## Type of change
- [ ] Added new language translation
- [x] Changed a currently existing translation

## Have you tested the changes you've made?
I can not test some of the changes because they are for unreleased upcoming game version.
- [ ] Yes
- [x] No

# Checklist:
- [x] I have made sure to not commit changes to other stuff than my own or the default english one
- [x] I have ran `EncodingNormalizer.exe` on my changed files before commiting 
   -  (Exception to this is when edits has __only__ been made in-browser)
- [x] I have made sure that I'm not submitting a duplicate translation 
- [x] I have not included any advertisements/pointers to non-game stuff other than author in the folder name

### CODE REVIEW

**Comment by realmbmc** [comment]
Please check this pull request guys, I am worrying that this updated localization won't get in next game's update...

**Comment by Dat-Joseph** [comment]
Could you please be so kind and take a look at the current existing English (default) translation,
Death Causes for example does have a line too much.
https://github.com/northwood-studios/SCPSL-Translations/blob/a0ffd1c470f0a3ada4807ee45888a2e2a147d301/Translations/ru/Death_Causes.txt
Then make a new Pull Request with all edited files in it, i dont quite understand all these deleted files and new added files. Just change the current ones.

**Comment by realmbmc** [comment]
@Dat-Joseph The description says
"P.S. I can not test some of the changes because they are for unreleased upcoming game version."

I will take a loot at new Death Causes, thanks

**Comment by Dat-Joseph** [comment]
For the next time i suggest you write your 'explanations' at the top of the template, i overread that part at the bottom of it.

**Comment by realmbmc** [comment]
@Dat-Joseph edited, thanks for explanation.
Changes that are used by current game version are tested and fully working.
New translation files and lines I can not test because I don't have even beta version of next update.

**Comment by Dat-Joseph** [comment]
That is not a big deal, there will be surely an open beta after the closed patreon beta, enough time to fix non-working translation parts while that. I will overlook your changes tomorrow evening.

**Comment by realmbmc** [comment]
@Dat-Joseph awesome! As soon as it live, I will test all changes and correct issues if found within 1-2 days.

**Comment by realmbmc** [comment]
@Dat-Joseph any news?

**Pull request merged**
