### PR TITLE
[sr-Cyrl-BA] Major improvements and new translations for the latest 12.0 beta for Serbian

### PR DESCRIPTION
**Pull request by LazarOroz**
# **SCP:SL Translation PR Template**

## **Language Name**
Serbian Bosnian (Cryllic)

## **State Type of change (New language, changed existing Etc.)**
Changed Existing (Everything new translated and improvements added)

# **Checklist:**
- [X] I have tested the translation changes in-game
- [X] I have made sure to not commit changes to multiple translations at the same time, or non-translation repo files
- [X] I have ran `EncodingNormalizer.exe` on my changed files before commiting 
   -  *( Exception to this is when edits has __only__ been made in-browser. If this is the case, also* ***check this box*** *)*
- [X] I have made sure that I'm **not** submitting a duplicate translation 
- [X] I have made sure my addition follows guidelines described in the [CONTRIBUTING.md](https://github.com/northwood-studios/SCPSL-Translations/blob/master/.github/CONTRIBUTING.md) file
- [X] I have made sure to label my translation folder by [Microsoft Language Tag Standards](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-lcid/a9eac961-e77d-41a6-90a5-ce1a8b0cdb9c)
   - Only in cases of **new** translations (Can be tested [Here](https://rextester.com/WDXPS97501)). Also check this box if the change is **not** a new translation
> For more information regarding game translations, please visit our [README](https://github.com/northwood-studios/SCPSL-Translations/blob/master/README.md) page.

### CODE REVIEW

**Comment by LazarOroz** [comment]
I'll finish the .json file later its very long for just one line and the language is probably not supported yet but I wanted Serbian to be ready.

**Comment by LazarOroz** [comment]
Translation checker errors fixed

**Comment by LazarOroz** [comment]
Jesus this took long

**Comment by LazarOroz** [comment]
the JSON check failure is beyond my control.

**Comment by LazarOroz** [comment]
Also if you please, add Gibu as a contributor as they qualify for manifest.json. They did a lot of changes resulting in more than 250 character modification of files which means they qualify

**Review by Rnen — APPROVED** [review]
Great work! Thanks

**Pull request merged**
