### PR TITLE
Update Death_Causes.txt

### PR DESCRIPTION
**Pull request by Arkira-Kuoyo**
# SCP:SL Translation PR Template

## Language
zh-Hant
## Type of change
- [] Added new language translation
- [x ] Changed a currently existing translation

## Have you tested the changes you've made?
- [ ] Yes
- [ x] No

# Checklist:
- [x ] I have made sure to not commit changes to other stuff than my own or the default english one
- [ ] I have ran `EncodingNormalizer.exe` on my changed files before commiting 
   -  (Exception to this is when edits has __only__ been made in-browser)
- [x ] I have made sure that I'm not submitting a duplicate translation 
- [x ] I have not included any advertisements/pointers to non-game stuff other than author in the folder name
- [x ] I have made sure to label my translation folder by [Microsoft Language Tag Standards](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-lcid/a9eac961-e77d-41a6-90a5-ce1a8b0cdb9c)
   - Only in cases of new translations

### CODE REVIEW

**Comment by SchrodingerSig** [comment]
被049-2杀死的文本补充下
第20行 Blunt trauma and minor scratches are present on the body.

**Comment by Arkira-Kuoyo** [comment]
> 被049-2杀死的文本补充下
> 第20行 Blunt trauma and minor scratches are present on the body.

額......請問為什麼要補充這個，英語原文本中並沒有這一句

**Comment by SchrodingerSig** [comment]
> > 被049-2杀死的文本补充下
> > 第20行 Blunt trauma and minor scratches are present on the body.
> 
> 額......請問為什麼要補充這個，英語原文本中並沒有這一句

？有啊
上面这条就是我直接复制粘贴来的

**Comment by Arkira-Kuoyo** [comment]
> > > 被049-2杀死的文本补充下
> > > 第20行 Blunt trauma and minor scratches are present on the body.
> > 
> > 
> > 額......請問為什麼要補充這個，英語原文本中並沒有這一句
> 
> ？有啊
> 上面这条就是我直接复制粘贴来的
> SCPSL-Translations/Translations/English (default)/Death_Causes.txt，第20行

哦，好吧，我是按照遊戲文件內的文本翻的，遊戲文件的文本沒有這一行

**Comment by SchrodingerSig** [comment]
> > > > 被049-2杀死的文本补充下
> > > > 第20行 Blunt trauma and minor scratches are present on the body.
> > > 
> > > 
> > > 額......請問為什麼要補充這個，英語原文本中並沒有這一句
> > 
> > 
> > ？有啊
> > 上面这条就是我直接复制粘贴来的
> > SCPSL-Translations/Translations/English (default)/Death_Causes.txt，第20行
> 
> 哦，好吧，我是按照遊戲文件內的文本翻的，遊戲文件的文本沒有這一行

这几天还更了两个文件，Connection_Errors.txt新增三条，Facility.txt的F1提示文本也有改动
其他最好也去检查下，毕竟距离上次繁中修改过去很久，我也不清楚和defualt差了多少

**Pull request merged**
