### PR TITLE
pt-BR megapatch translation + correction of typos and bugs

### PR DESCRIPTION
**Pull request by firer2009**
# SCP:SL Translation PR Template

## Language
(Replace this text with language name)

## Type of change
- [ ] Added new language translation
- [X] Changed a currently existing translation

## Have you tested the changes you've made?
- [X] Yes
- [ ] No

# Checklist:
- [X] I have made sure to not commit changes to other stuff than my own or the default english one
- [X] I have ran `EncodingNormalizer.exe` on my changed files before commiting 
   -  (Exception to this is when edits has __only__ been made in-browser)
- [X] I have made sure that I'm not submitting a duplicate translation 
- [X] I have not included any advertisements/pointers to non-game stuff other than author in the folder name
- [ ] I have made sure to label my translation folder by [Microsoft Language Tag Standards](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-lcid/a9eac961-e77d-41a6-90a5-ce1a8b0cdb9c)
   - Only in cases of new translations

### CODE REVIEW

**Comment by firer2009** [comment]
sorry for the delay. i have now removed hints.txt and translated everything that came up in the latest patch, so the pt-BR folder is 100% updated and normalised.

**Comment by firer2009** [comment]
i am not sure how to undo the changes (normalisation) i've done on the other languages though. is there a way to only merge the pt-BR folder and nothing else to the master branch? (i am kinda new to github)

**Comment by Rnen** [comment]
Closing this as it still has conflicts due to changes to other languages than pt-Br.
I suggest copying out the pt-Br folder, downloading a fresh version of our files, then creating a new PR.
This will avoid the issue stated above.
For other guidance please see our guide at [How To Contribute](https://github.com/northwood-studios/SCPSL-Translations#how-to-contribute) where you can find both a written guide and a video on the use of our GitHub.

**Comment by Rnen** [comment]
And i personally apologize for the lack of response on this matter.

**Pull request closed without merging**
