### PR TITLE
Italian translation update

### PR DESCRIPTION
**Pull request by terminator-97**
# SCP:SL Translation PR Template

## Language
Italian

## Type of change
- [ ] Added new language translation
- [x] Changed a currently existing translation

## Have you tested the changes you've made?
- [x] Yes
- [ ] No

# Checklist:
- [x] I have made sure to not commit changes to other stuff than my own or the default english one
- [ ] I have ran `EncodingNormalizer.exe` on my changed files before commiting 
   -  (Exception to this is when edits has __only__ been made in-browser)
- [x] I have made sure that I'm not submitting a duplicate translation 
- [x] I have not included any advertisements/pointers to non-game stuff other than author in the folder name

### CODE REVIEW

**Comment by Rnen** [comment]
Please rename your Pull Request title. Currently: `Patch 5`

**Comment by terminator-97** [comment]
@Rnen done

**Comment by ShingekiNoRex** [comment]
Please resolve the conflicts

**Comment by terminator-97** [comment]
@ShingekiNoRex done

**Comment by ShingekiNoRex** [comment]
Some lines are missing

> ===Italian===
File Connection_Errors.txt has 31 lines, expected 33

**Comment by ShingekiNoRex** [comment]
And please run `EncodingNormalizer.exe`

**Pull request merged**
