### PR TITLE
Ukrainian translation full update

### PR DESCRIPTION
**Pull request by Rayfulrand**
# SCP:SL Translation PR Template

## Language Name
Ukrainian (uk)

## State Type of change (New language, changed existing Etc.)
- Translation of not-translated files.
- Complete editing of previously translated files.
- Translation of achievements and Rich Presence
- Updating UK line in credits file

# Checklist:
- [x] I have tested the translation changes ingame
- [x] I have made sure to not commit changes to multiple translations at the same time, or non-translation repo files
- [x] I have ran `EncodingNormalizer.exe` on my changed files before commiting 
- [x] I have made sure that I'm **not** submitting a duplicate translation 
- [x] I have made sure to **not** included any advertisements/pointers to non-game stuff other than the translation author in the credits file
- [x] I have made sure to label my translation folder by [Microsoft Language Tag Standards]

### CODE REVIEW

**Comment by Rayfulrand** [comment]
Update: Abilities are updated, aligned with English

**Comment by Rayfulrand** [comment]
Hi!
I've tested game again with new update and fixed last things to be fixed in new menu. Can you please push all these changes to live environment? With store description and achievements?

**Comment by Dat-Joseph** [comment]
Hey there!
An update to your Pull Request: We received feedback from a user (not one of those you provided)
He said the translation looks good! But he also had some criticism:
"change "NEW_ACHIEVEMENT_4_28_NAME" to "Хеловін!" instead of Геловін because хеловін is more common" 
Maybe you want to change that or let it be like you translated it. Its up to you. 
We will approve your pull request shortly after you replied :)

**Comment by Rayfulrand** [comment]
Hi @Dat-Joseph, thank you for response and this feedback.
I'd rather not change **Г**еловін то **Х**еловін. Even if one letter differs only, it has quite a big difference in concepts of our language and its perception by people.
If shortly, reasons not to change: 
- we have strict rules of transliteration that requires using **Г г** character for English **H h** transcription, and this is the case;
- all professional translators and editors use **Г** in Ukrainian literature (most modern book publishers), movies (since at least 2010), and now in most games as well.

But it's really nice to hear people check even this!
Thank you again!

**Comment by Dat-Joseph** [comment]
Alright. With that we approve your Pull Request. 
The translation should be in the next beta patch then.

**Comment by Rayfulrand** [comment]
Thank you!

**Pull request merged**
