### PR TITLE
updated version of TR

### PR DESCRIPTION
**Pull request by ralncZ**
Previous translation was outdated, this version is more accurate and updated for SCP Foundation. This should be better for the Game and Turkish Players to understand.

# SCP:SL Translation PR Template

## Type of change
- [ ] Added new language translation
- [X] Changed a currently existing translation

## Have you tested the changes you've made?
- [X] Yes
- [ ] No

# Checklist:
- [X] I have made sure to not commit changes to other stuff than my own or the default english one
- [X] I have ran `EncodingNormalizer.exe` on my changed files before commiting 
   -  (Exception to this is when edits has __only__ been made in-browser)
- [X] I have made sure that I'm not submitting a duplicate translation 
- [X] I have not included any advertisements/pointers to non-game stuff other than author in the folder name

### CODE REVIEW

**Comment by MichalPetryka** [comment]
Please take a look at english files here and also translate new things from there

**Comment by Dat-Joseph** [comment]
A new file has been added to the English Default, for your notice.

**Comment by ralncZ** [comment]
[Abilities.txt](https://github.com/northwood-studios/SCPSL-Translations/files/3610584/Abilities.txt)
[InventoryErrors.txt](https://github.com/northwood-studios/SCPSL-Translations/files/3610585/InventoryErrors.txt)
[Class_Nicknames.txt](https://github.com/northwood-studios/SCPSL-Translations/files/3610586/Class_Nicknames.txt)
[Class_Bio.txt](https://github.com/northwood-studios/SCPSL-Translations/files/3610587/Class_Bio.txt)

I think this should work, sorry for being late. :)

**Comment by MichalPetryka** [comment]
Please include those files as parts on the PR instead

**Comment by MichalPetryka** [comment]
Please remove tutorial files.

**Comment by Rnen** [comment]
@ralncZ Please reopen a Pull Request after taking the steps described above.

**Pull request closed without merging**
