### PR TITLE
Revision on Thai translation.

### PR DESCRIPTION
**Pull request by DatPanDat**
# SCP:SL Translation PR Template

## Language Name
Thai

## State Type of change (New language, changed existing Etc.)
Changed existing.
(Wanted to note that while most of the characters errors that turn into a square is gone, there is still quite a number of them in the F1 menu. There might be more but I couldn't remember where.)

# Checklist:
- [x] I have tested the translation changes ingame
- [x] I have made sure to not commit changes to multiple translations at the same time, or non-translation repo files
- [x] I have ran `EncodingNormalizer.exe` on my changed files before commiting 
   -  (Exception to this is when edits has __only__ been made in-browser. If this is the case, also check this box.)
- [x] I have made sure that I'm **not** submitting a duplicate translation 
- [x] I have made sure to **not** included any advertisements/pointers to non-game stuff other than the translation author in the credits file
- [x] I have made sure to label my translation folder by [Microsoft Language Tag Standards](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-lcid/a9eac961-e77d-41a6-90a5-ce1a8b0cdb9c)
   - Only in cases of **new** translations (Can be tested [Here](https://rextester.com/WDXPS97501)). Also check this box if the change is **not** a new translation
> For more information regarding game translations, please visit our [README](https://github.com/northwood-studios/SCPSL-Translations/blob/master/README.md) page.

### CODE REVIEW

**Comment by DatPanDat** [comment]
I wanted to resolve the conflicts, but the button is grayed out and said that it is too complex to be edit using the web editor, the "View on GitHub Desktop" doesn't appear, and it also said that "Only those with write access to this repository can merge pull requests". Unless I actually can't resolve it myself, or I have to use Git to resolve it, (Which I have absolutely no clue how to use.) could someone help me with this?

**Comment by Rnen** [comment]
> I wanted to resolve the conflicts, but the button is grayed out and said that it is too complex to be edit using the web editor, the "View on GitHub Desktop" doesn't appear, and it also said that "Only those with write access to this repository can merge pull requests". Unless I actually can't resolve it myself, or I have to use Git to resolve it, (Which I have absolutely no clue how to use.) could someone help me with this?

Yeah i was looking into this yesterday before i was interrupted by something :sweat_smile: 
Handling it shortly

**Comment by Rnen** [comment]
There we go, merge conflicts solved.
Please re-check that i didn't mess anything up :grin:

**Comment by DatPanDat** [comment]
For the Thai language, everything seems to be okay. But there was several changes to various languages in your commit. Would that be okay?

**Comment by Rnen** [comment]
> For the Thai language, everything seems to be okay. But there was several changes to various languages in your commit. Would that be okay?

Yeah don't mind that, i was just catching your branch up to ours. :grin:

**Review by Rnen — APPROVED** [review]

**Pull request merged**
