### PR TITLE
Ukrainian up to date update 

### PR DESCRIPTION
**Pull request by Rayfulrand**
# SCP:SL Translation PR Template

## Language Name
Ukrainian

## State Type of change (New language, changed existing Etc.)
Update to align with current English version, bugfixes and improvements based on another contribution and testing.

# Checklist:
- [x] I have tested the translation changes ingame
- [x] I have made sure to not commit changes to multiple translations at the same time, or non-translation repo files
- [x] I have ran `EncodingNormalizer.exe` on my changed files before commiting 
   -  (Exception to this is when edits has __only__ been made in-browser. If this is the case, also check this box.)
- [x] I have made sure that I'm **not** submitting a duplicate translation 
- [x] I have made sure to **not** included any advertisements/pointers to non-game stuff other than the translation author in the credits file
- [x] I have made sure to label my translation folder by [Microsoft Language Tag Standards](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-lcid/a9eac961-e77d-41a6-90a5-ce1a8b0cdb9c)
   - Only in cases of **new** translations (Can be tested [Here](https://rextester.com/WDXPS97501)). Also check this box if the change is **not** a new translation

### CODE REVIEW

**Comment by MajorFox-MJ** [comment]
Please let the manifest.json like it was before, it shouldn't be modified. (It should keep the Ukrainian data).
https://github.com/northwood-studios/SCPSL-Translations/pull/693/files#diff-867ec1a6ba8809565bbc260684eee4a8cbb15f1e9869e35c13c4516658d420fb

**Comment by Rayfulrand** [comment]
@MajorFox-MJ thank you, updated manifest and another file (for some reason Github reverted my last changes for it, possibly I did something wrong). 
That is why I'm for CrowdIn:)

**Comment by Rnen** [comment]
See https://github.com/Rayfulrand/SCPSL-Translations/pull/1
Required for checks.

**Comment by Rnen** [comment]
Closed due to missing requirements. Feel free to re-open a PR once the previously mentioned requirement are met.

**Pull request closed without merging**
