### PR TITLE
Czech translation

### PR DESCRIPTION
**Pull request by Cezhar16**
# SCP:SL Translation PR Template

## Language Name
(Czech)

## State Type of change (New language, changed existing Etc.)
(Czech translation update of new untranslated things and corrections of old translations)
I tested it in the game and it all works and credit update with my nickname
# Checklist:
All new translate
- new DecontaminationDisplays.txt
- new Doors.txt
- new NewMainMenu.txt (translated new menu, not translated yet)
- new microhid.txt
- new Intercom and Intercom_door_sign.txt
- new Keybinds.txt
- update scp079.txt for better gameplay plus better customization
- new nuke and nuke_silo_sign.txt
- new report_form.txt
- new SCP_Interfaces.txt
- new weaponsmod(částečný překlad)
- new workstation
- update manifest (I added my nickname because I also translated and I will continue to translate)
- add czech steam achievements
- add czech rich presence

### CODE REVIEW

**Comment by Cezhar16** [comment]
is the problem with that? Idk, this is first time for me

**Comment by Cezhar16** [comment]
where is problem ? idk

**Comment by Rnen** [comment]
image
Approving it, but feel free to add these missing lines in the future. :slightly_smiling_face:

**Review by Rnen — APPROVED** [review]

**Comment by Cezhar16** [comment]
thanks

**Pull request merged**
