### PR TITLE
Add new language zh-CN

### PR DESCRIPTION
**Pull request by SchrodingerSig**
## Language
zh-CN

## Type of change
- [x] Added new language translation
- [ ] Changed a currently existing translation

## Have you tested the changes you've made?
- [x] Yes
- [ ] No

# Checklist:
- [x] I have made sure to not commit changes to other stuff than my own or the default english one
- [x] I have ran `EncodingNormalizer.exe` on my changed files before commiting 
   -  (Exception to this is when edits has __only__ been made in-browser)
- [x] I have made sure that I'm not submitting a duplicate translation 
- [x] I have not included any advertisements/pointers to non-game stuff other than author in the folder name
- [x] I have made sure to label my translation folder by [Microsoft Language Tag Standards](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-lcid/a9eac961-e77d-41a6-90a5-ce1a8b0cdb9c)
   - Only in cases of new translations

### CODE REVIEW

**Comment by SchrodingerSig** [comment]
Apologys for the members that not related to this but still being annoyed(?
Rex really dont want to solve this, sad ;-;
since the current zh-Hans' word/grammar uses, definition of some word, are heavily different to my translation, so im taking the zh-CN
you guys can add this into game anytime, it dont need to be in MP2 or even MP3, no rush
since ive been inveigle to do all the translation/correction for Rex and his friends, i need a clear line to divide me and them

**Comment by SchrodingerSig** [comment]
(some languages have **Custom Audio**??? wow thats sick :D)
(How does that works, im quite interest about that)

**Comment by Rnen** [comment]
## Custom Audio
Custom audio files are no longer supported and are being phased out due to development issues.
Reimplementation of the ability to use custom sound files will possibly return later.

---
## zh-Hans
Also, we have asked more (non-staff) Chinese people to take a look at the zh-Hans dispute, just to make sure.

---
The current PR will be reviewed by apropriate staff soon.

**Comment by SchrodingerSig** [comment]
note: zh-Hans/zh-CN
the corpse's description is still in English (can't been shown correctly)

**Comment by SchrodingerSig** [comment]
Just realise, Achievement also need some changed to fit the current translation
狂暴 → 狂怒
口袋空间 → 口袋次元
O5钥匙卡 → O5级别钥匙卡
电磁炮 → 电浆喷射器
Micro HID / MicroHID → Micro H.I.D.
some specifit corrections:
成就“纳尼？！”描述：“一个科学家”改成“一名科学家”
成就“万圣节/圣诞节快乐！”描述：“游玩万圣节/圣诞节版本的游戏。”改为“在万圣节/圣诞节期间游玩游戏。”
成就“可口可乐”描述：“SCP-207的影响下”改为“SCP-207的效果中”为好，不过这句问题不大可以无视
成就“毫无感觉”描述：“会杀死你的” 直接用“致命的”不好吗（？
成就“不了，谢谢”描述：“给MicroHID充电或开火” Micro格式上面写了，“充电或开火”改为“蓄能或喷射”为好，毕竟充电和下面真的充电冲突了

（note: 新老成就的翻译应该是两个人，翻译风格和用词能感觉出不同，
老成就的翻译更偏向于按照成就描述对名称进行即兴创作，我没啥大意见，但是部分真的偏离原意过多了，比如为了基金会！(原文Gear up, Boys!)；O5议会（原文Overpowered!）；基金会之耻（原文The tables have turned...，这句问题很大，主动句变成被动句了）；完成职责（原文If you want something done right...）；电磁炮（原文Microwave Meal）
（我好像把问题比较大的全部都列举出来了）
新成就的翻译问题就比较大了，我毫不客气地说这根本就是瞎翻译，成就名称6个里4个跟原句挂不上边。别的不说，就我不知道是谁翻的情况下，只看文本，就一个建议：把他炒了）

**Comment by SchrodingerSig** [comment]
https://docs.google.com/document/d/1oLbZJq5sSl55CgzR1sZmFTIbLJFtvyxWZmRjiLksxnY/edit?usp=sharing
Heres a doc that we can discuss Achievement translations with (ffs someone please use it)

**Comment by SchrodingerSig** [comment]
note: game glitch
SCP079, back into facility from gate B elevator will spawn to gate A

**Comment by SchrodingerSig** [comment]
Im slowly changing the text so it will more based on game

**Comment by SchrodingerSig** [comment]
note：zh-CN
something wrong with summary, gonna check the text later

**Comment by SchrodingerSig** [comment]
> note：zh-CN
> something wrong with summary, gonna check the text later

oooook know the reason

**Comment by Rnen** [comment]
Management Response - Warning
---
> 就一个建议：把他炒了）

Please note that continued attacks directed at staff is absolutely not tolerated, and may result in dismissal of this PR. 
Under no circumstance are we obliged to handle your request, and we will continue to not do so untill you drop the attitude. Respect the studio staff, and you shall receive the same level of respect.
Thanks.

### - Evan, Backend Manager

**Comment by SchrodingerSig** [comment]
> ## Management Response - Warning
> > 就一个建议：把他炒了）
> 
> Please note that continued attacks directed at staff is absolutely not tolerated, and may result in dismissal of this PR.
> Under no circumstance are we obliged to handle your request, and we will continue to not do so untill you drop the attitude. Respect the studio staff, and you shall receive the same level of respect.
> I really want this to go as smoothly as possible, and where everyone is happy, but this is proving difficult with your attitude. So please behave.
> Thanks.
> 
> ### - Evan, Backend Manager

uh... thats not what this ment to mean ;-;
apologize for my improper laguage use

**Comment by SchrodingerSig** [comment]
> Like can be seen here
> https://github.com/northwood-studios/SCPSL-Translations/blob/e2ef929ac4b4c569518978047b500d087096dcf6/Translations/English%20(default)/Facility.txt#L33-L34
> 
> 
> English does not use the `{0}` system. Please use the same format as english.

the translations in game are all been changed to {0} format (include English (defualt) )
im kind confused

**Comment by SchrodingerSig** [comment]
miss click x(

**Comment by SchrodingerSig** [comment]
NOTE: Special thanks to No_149, for pointing out the improper translations for MTF's military rank
公告：感谢贴吧用户No_149指出九尾狐的军衔翻译问题
The current translation for Lieutenant and Commander are not fitting to the rank irl
当前对于Lieutenant和Commander的翻译有严重问题
Based on the proper translation for these two ranks, heres the changes I made:
现根据实际军衔名称，进行以下修改：
Lieutenant 士官 → 尉官
Commander 指挥官 →  校官

**Comment by Miiers** [comment]
Don't let the players googling meaning of military rank.
This's just a game. 
We need localized and accurate translation.
Thanks!
Lieutenant→副官
Commander 保留指挥官翻译

**Comment by SchrodingerSig** [comment]
> Don't let the players googling meaning of military rank.
> This's just a game.
> We need localized and accurate translation.
> Thanks!
> Lieutenant→副官
> Commander 保留指挥官翻译

First of all, 副官 is not related to any Military Rank, same as 指挥官, thats why your change is unreasonable.
Second, because this is a game, and i'm a translator, i wont leave this obvious mistake in the game, thats my duty isnt it? ;)
(2.5, i dont think Chinese players cant tell the difference between 尉官 and 校官... just saying that)
Third, since you are FINALLY willing to communicate, so this one is only for you. 这件事会发生，是由于你的两条不规范的动态导致的，请不要推脱责任，在现阶段把对我的侮辱性称谓揽到自己身上是很可笑的行为。我希望您能认清你的立场，你的身份(工作室成员+#208PR的修改人之一)(有利益相关)，如果您真的想让这件事和平解决，还请继续保持沉默，或是认真态度，正面地来和我交流，而不是以上来就威胁逼迫的形式。（补充：随便删我正常和玩家讨论的贴子和楼是不是有些过分了。不过我有截图所以不怕）

**Comment by SchrodingerSig** [comment]
Welp, xiaoyi just banned me again
ok boomer, if thats what you want, then i guess i have to deal with it
be prepared ;)

**Comment by SchrodingerSig** [comment]
@Miiers @Tychus-Xiaoyi @ShingekiNoRex

**Comment by SchrodingerSig** [comment]
公告：经贴吧用户临晨之风-提醒，军衔应与SCP中分翻译为基础
二次修改如下：
Lieutenant 改为“中尉”
Commander 回归“指挥官”
（参考文本：SCP-363，为数不多的同时出现上述两个词且被翻译的页面）

**Comment by Dat-Joseph** [comment]
Can we keep the Pull Request please related to the translation. Any outside interactions such as discord bans do not belong here. Thank you.

**Comment by SchrodingerSig** [comment]
> Can we keep the Pull Request please related to the translation. Any outside interactions such as discord bans do not belong here. Thank you.
> 
> Edit: Related to your 4th last message.

roger that, ill beware of
do i need delete the previous comments?

**Comment by SchrodingerSig** [comment]
i know i should keep silent and waiting at ths point but...
is anyone gonna look over or update the Chinese Achievement?

https://docs.google.com/spreadsheets/d/1h_bIHwdT6EHfGmhQxflYefJZHSkLsoQQLTEYina1lTY/edit?usp=sharing
I created a new document for chinese achievement only. ill keep it updated, and if any chinese speaking staff can read that by the way and leave some comments/suggestion, that will be great

**Comment by Miiers** [comment]
Iincomprehensible...I think most of the achievements of translation are perfect. It's perfect combination of translation text and Chinese local scpsl memes.But u just turn the text into a textbook translation.Thank u for ur advice, but most real scp fans won't accept it

**Comment by Tychus-Xiaoyi** [comment]
Iincomprehensible...I think most of the achievements of translation are perfect. It's perfect combination of translation text and Chinese local scpsl memes.But u just turn the text into a textbook translation.Thank u for ur advice, but most real scp fans won't accept it

**Comment by SchrodingerSig** [comment]
> Iincomprehensible...I think most of the achievements of translation are perfect. It's perfect combination of translation text and Chinese local scpsl memes.But u just turn the text into a textbook translation.Thank u for ur advice, but most real scp fans won't accept it

so you mean translation like 混沌分裂者的资质, 可口可乐, 电磁炮, 幸存者, ect, witch contain several level of misleading or mistranslation are *ok in the game*?
using scp memes are ok, but at lease you gotta use the proper meme right? is accurate translation more important or abuse memes more important?
and unify the text aint important? 
no fence but now i really wanna query your English level just by that. I will collect more feedback from community, so there.

**Comment by Tychus-Xiaoyi** [comment]
OK, as u like, This's the community feedback you need, u lost completely:https://cdn.discordapp.com/attachments/589007098822787093/657762361414909972/Screenshot_20191221_095110.jpg
nothing but 电磁炮 should be revised :)

**Comment by SchrodingerSig** [comment]
> OK, as u like, This's the community feedback you need, u lost completely:https://cdn.discordapp.com/attachments/589007098822787093/657762361414909972/Screenshot_20191221_095110.jpg
> nothing but 电磁炮 should be revised :)

what about show them some examples? ;) picking from 4 pre made options shows nothing.
you cant avoid these mistranslations, so just face them

**Comment by SchrodingerSig** [comment]
https://docs.google.com/spreadsheets/d/1h_bIHwdT6EHfGmhQxflYefJZHSkLsoQQLTEYina1lTY/edit?usp=sharing
Just finished listing all the achievement and change suggestions, so i just repost it again.
I really hope I can discuss with stuffs that are **responsible enough** to the translations. "Abusing memes and dont fix translation errors" is probably the most laughable thing for me in this year

**Comment by SchrodingerSig** [comment]
note: my discussion in chinese community (the one that for collecting translation-related feed back) have been deleted by xiaoyi
im sad now ;-;

**Comment by SchrodingerSig** [comment]
about the discription for SCP-268
the defualt text (aka the English) used the word "invisible", which is not appeard in the original SCP file
since the game is the re-create of SCP universe, and 207/108 dont exactly function as the file says, im considering it is not conflict with the original file just by now
gonna see if it will be edit in the future, or ill probably keep this line(...?)

**Comment by SchrodingerSig** [comment]
btw the discription for Weapon Manager Tablet need a upgrade, it require a workstaion to modify weapons, and can only drop ammo without it
I made my own discription for temporary use, but still, waiting for the changes for defualt text
- Drop Ammo
- Upgrade Weapon (workstation)
- Start the Generator Countdown (Generator)

**Comment by SchrodingerSig** [comment]
theres a typo in zh-Hans
in version_7-0-0.txt, which one of "武器控制面板" have been typed to ”武器**管理**面板“
since im currently having this pull request, and seems they dont want me participate zh-Hans anymore (which is nice), im just gonna say it here, hope someone see this

**Comment by SchrodingerSig** [comment]
fun fact when i re-re-re-checking all the translations:
just find that the official name for all kaycard is "Access Card (权限卡)" (from Abilities.txt), so "Chaos Insurgency Access Device" cant be translate to 破解装置(breaching tool) due to the function of both CIAD and other keycard... just saying that

**Comment by SchrodingerSig** [comment]
since the **BIG SINKHOLE THAT SLOWS YOU DOWN** have been added to the game, its good to re-translate the word "sinkhold" based on how it function in game now
the current transltion for that is "次元洞" (from the last major update, based on its teleport function), and im reversing it back to "渗穴", one of the other translation from the last major version of the game
again, this change is temporary, ill try to find a better translation later on

**Comment by SchrodingerSig** [comment]
这段注解主要还是中文相关，所以不用英文了
之前说过，部分SCP的技能由于PR176改得太简了所以只是适当进行了修改，主体框架仍旧采用176之前的文本。现在结果斟酌，这些文本的修改如下：
绝唱：太绕了，后半段有关献祭的文本也出现了不符合游戏内容的文本，所以修改时借鉴了当前英文文本修改
口袋次元：不知道是不是我的错觉，有时候口袋次元会刷两扇出口？姑且先把八选一的内容删了
学舌：拿原文来翻译难度颇大（毕竟语法什么的翻中文还真没法一句话解释清楚），所以我自由发挥了
近乎无敌：修改语序

**Comment by SchrodingerSig** [comment]
*Death_Causes.txt have been updated to the newest version*

**Comment by SchrodingerSig** [comment]
one of my frind pointed out some small issue, which im appreciate for that √

**Comment by SchrodingerSig** [comment]
question about Class_Descriptions.txt: why only penut, larry, doctor and zombies has skill introductions -- will skill intro for shy guy, dogs been add in the future? 🤔

**Comment by Rnen** [comment]
> question about Class_Descriptions.txt: why only penut, larry, doctor and zombies has skill introductions -- will skill intro for shy guy, dogs been add in the future?

The game constantly changes, and with that, how the characters work.
Reworks & tweaks for almost all SCP are long-term planned.

**Comment by SchrodingerSig** [comment]
有关COM-15 Sidearm的翻译
Sidearm属于随身配枪，枪身较小便于携带与取出，一般用于应急自卫
之前我翻译的时候采用了”便携式“这个翻译（能随身携带）
但经过斟酌，我还是决定忠于枪名（COM→Compact），将其更改为”紧凑型“
算是比较大的修改，公示下

**Comment by SchrodingerSig** [comment]
btw Ive also update the achievement change suggestion sheet, if anyone got time, please **please** read that again

**Comment by SchrodingerSig** [comment]
> 收容失效 is an official translation, no need to annotation, too long text will be too conspicuous
的确过长，现在已经移除

> Note English default text: COM-15 _Sidearm_, it's not a real pistol model
对于枪名的修改是基于其名字内的COM(compact)考虑的， 其实翻成”自卫武器“会更合理，但是这样就打乱枪名的格式了
（顺带我去官方wiki上看了眼，这枪的模型是OTs-33 Pernach和PR-15 handgun的结合体... 挺有意思的）

> Because involves related terms, Chinese is more convenient for you to explain. 是这样的，服务器可以通过例如enforce_same_asn的相关config设置来禁止非同一个地区的玩家进入服务器，所以将文本更改为:
> 
> 服务器名称或是信息中可能会包含相关信息。
> <size=80>断开连接\n基于你所在地理位置，服务器阻止了你的连接。\n服务器名称或是信息中可能会包含相关信息
> 
> 更加妥当。
已经修改，感谢

**Comment by SchrodingerSig** [comment]
(成就真的麻烦静下心来看一下，名称要是有异议就讨论呗，描述的文本统一和typo总得修一修吧)

**Comment by SchrodingerSig** [comment]
wait a sec.... of the in game translation have been updated (i mean MP2, not this PR), should the game description on steam page also get a update (for unify)? 
ill find the english description later, and see if i can do something with that

**Comment by SchrodingerSig** [comment]
yeah the translation for "ABOUT THIS GAME" on steam page need a update
the discription for the later added SCPs is missing

**Comment by SchrodingerSig** [comment]
holy shi- im impressed
surely it got some misunderstanding, but the overall accuracy and localization is good
damn im start curious, why the in-game translation was SO bad (before MP2) when you guys can find this level of translator
anyway i put the compare version under the achivement
https://docs.google.com/spreadsheets/d/1h_bIHwdT6EHfGmhQxflYefJZHSkLsoQQLTEYina1lTY/edit?usp=sharing

**Comment by SchrodingerSig** [comment]
成就翻译修改建议 更新：
It's always left, Brothers! 一路向西，伙计 → 一路向左，伙计 (暂定)
B站用户“改名后又是新号啦”提出左手法则不适合指定具体方位，所以暂时先把它改成向左

**Comment by SchrodingerSig** [comment]
(im still waiting for Chinese Achievement Localization update, i guess they just dont want to fix that "Escape the facility in **2** minutes" typo)

**Comment by SchrodingerSig** [comment]
修改了下所有SCP的描述，明确两个SCP获胜条件的主次关系
- 阻止人员逃离（主要）
- 杀死所有人（次要）

**Comment by SchrodingerSig** [comment]
有关Lieutenant的翻译（再次）
我因为在翻其他游戏的文本时又翻到了这词，所以我就专门去查了一下这词的意思（上次只查了军衔）
下列两个是其作为名词的意思
1、a commissioned officer ranking between lieutenant junior grade and lieutenant commander. （军衔，中文翻作中尉）
2、a person who holds an office, civil or military. （队长之类的角色，比如说警长之类的）
考虑到MTF属于私人组建部队，Commander也采用了非军衔的“指挥官”，所以其实Lieutenant翻作“队长”或是“长官”比较好？？？
于是我又去查了下Cadet的意思，它指的是“a student in training for service as a commissioned officer”，也就是说是它其实是作为Commander候补的学员，“新兵”这个译文不太合适，他们毕竟并没有正式编制进部队

总而言之，下面是修改（绝对不会错的翻译）
Cadet：九尾狐新兵 → 九尾狐学员
Lieutenant：九尾狐中尉 → 九尾狐队长
Commander：九尾狐指挥官 (维持不变)

**Comment by Tychus-Xiaoyi** [comment]
I'll consider that, but I′ll not adopt it,  because your approach is the same as put it on my face with an Oxford dictionary. btw you're still insulting me on sns :)

**Comment by SchrodingerSig** [comment]
> I'll consider that, but I'll not adopt it, because your approach is the same as put it on my face with an Oxford dictionary. btw you're still insulting me on sns :)

Im just fixing these "improper translations", if you know what are you doing, you wont be judging with changes with explanations ;)

**Comment by SchrodingerSig** [comment]
#320 
dont make me disappoint again ;) hope "we" can have more formal discussions

**Pull request closed without merging**
