### PR TITLE
zh-hant correction

### PR DESCRIPTION
**Pull request by Arkira-Kuoyo**
# SCP:SL Translation PR Template

## Language Name
zh-Hant

## State Type of change (New language, changed existing Etc.)
Change existing

# Checklist:
- [x ] I have tested the translation changes ingame
- [ x] I have made sure to not commit changes to multiple translations at the same time, or non-translation repo files
- [ ] I have ran `EncodingNormalizer.exe` on my changed files before commiting 
   -  (Exception to this is when edits has __only__ been made in-browser. If this is the case, also check this box.)
- [ x] I have made sure that I'm **not** submitting a duplicate translation 
- [x ] I have made sure to **not** included any advertisements/pointers to non-game stuff other than the translation author in the credits file
- [ x] I have made sure to label my translation folder by [Microsoft Language Tag Standards](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-lcid/a9eac961-e77d-41a6-90a5-ce1a8b0cdb9c)
   - Only in cases of **new** translations (Can be tested [Here](https://rextester.com/WDXPS97501)). Also check this box if the change is **not** a new translation

### CODE REVIEW

**Comment by Tychus-Xiaoyi** [comment]
請先更新一下ReportForm.txt,它增加了新的文本
Please update ReportForm.txt

**Comment by X-EROS** [comment]
你有冇查過SR係咩先改做狙擊步槍? 如果冇唔該你改返佢

**Comment by Arkira-Kuoyo** [comment]
> 你有冇查過SR係咩先改做狙擊步槍? 如果冇唔該你改返佢

我查咗過 SR係指“Sniper Rifle”，並唔喺“突擊步槍”（另外我嘅patch唔知出D乜問題冇辦法更改）

**Comment by ShingekiNoRex** [comment]
> > 你有冇查過SR係咩先改做狙擊步槍? 如果冇唔該你改返佢
> 
> 我查咗過 SR係指“Sniper Rifle”，並唔喺“突擊步槍”（另外我嘅patch唔知出D乜問題冇辦法更改）

SR means Standard Rifle

**Comment by Arkira-Kuoyo** [comment]
> > > 你有冇查過SR係咩先改做狙擊步槍? 如果冇唔該你改返佢
> > 
> > 
> > 我查咗過 SR係指“Sniper Rifle”，並唔喺“突擊步槍”（另外我嘅patch唔知出D乜問題冇辦法更改）
> 
> SR means Standard Rifle

Well...I was wrong...I will change it back...

**Pull request closed without merging**
