### PR TITLE
add new lanwage zh-CN

### PR DESCRIPTION
**Pull request by SchrodingerSig**
## Language
zh-CN

## Type of change
- [x] Added new language translation
- [ ] Changed a currently existing translation

## Have you tested the changes you've made?
- [x] Yes
- [ ] No

# Checklist:
- [x] I have made sure to not commit changes to other stuff than my own or the default english one
- [x] I have ran `EncodingNormalizer.exe` on my changed files before commiting 
   -  (Exception to this is when edits has __only__ been made in-browser)
- [x] I have made sure that I'm not submitting a duplicate translation 
- [x] I have not included any advertisements/pointers to non-game stuff other than author in the folder name
- [x] I have made sure to label my translation folder by [Microsoft Language Tag Standards](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-lcid/a9eac961-e77d-41a6-90a5-ce1a8b0cdb9c)
   - Only in cases of **new** translations (Can be tested [Here](https://rextester.com/WDXPS97501))

### CODE REVIEW

**Comment by SchrodingerSig** [comment]
when will you learn... this is not how you solve the problem :/

**Comment by SchrodingerSig** [comment]
#332 #244

**Comment by SchrodingerSig** [comment]
something i want to make clear: this PR is ment to be "adding a new language that separate from zh-Hans" instead "making suggest to zh-Hans"
feel free to keep the *out dated* text from my previous translations, since these are now officially "you guys'", and before the zh-CN get pass and merg into the main branch, technically i still have full control to it, which ill keep doing regular update/fixs at here √
everyong is just doing their job, right? ;)

**Comment by SchrodingerSig** [comment]
MenuWarnings.txt:
i somehow typed "\n" to "/n" x(
yeah... kind shame

**Comment by SchrodingerSig** [comment]
Created Connection_Info.txt n LoadingHints.txt
waiting for more hints been added

**Comment by SchrodingerSig** [comment]
ok, drag all the file into my branch is surely a bad idea x(

**Comment by SchrodingerSig** [comment]
想不出Raiding怎么翻译合适
姑且先这么翻着

**Comment by SchrodingerSig** [comment]
不是很确定整体举报系统的修改会是怎么样
cheating, griefing or raiding这句我觉得有很大几率会出界，虽说我也没啥好想法来缩减这一句

**Comment by qwq233** [comment]
zh-Hans就是zh-cn

**Comment by SchrodingerSig** [comment]
> zh-Hans就是zh-cn

你可能不知道之前发生了什么，总之这个PR是要和zh-Hans分离开来

**Comment by SchrodingerSig** [comment]
考虑到096重做后将拥有随时间回复的AHP，目前对AHP的译名“临时血量”字面意思与其机制会有所偏差（就目前来说如此，毕竟目前释出的演示096的AHP更类似呼吸回血，而不是像肾上腺素那样属于临时增加血量上限）
目前我先姑且将其改为“忍耐值”，该译名基于肾上腺素的描述：“临时提升对疼痛的*忍性*。”

**Comment by SchrodingerSig** [comment]
关于头衔：
这玩意我翻成啥还真不算数，先等等看zh-Hans怎么翻吧。

**Comment by SchrodingerSig** [comment]
096技能翻译完成 √
我看“忍耐值”这个译名和096技能描述挺搭的所以先留着了
吐槽zh-Hans的翻译错误
吐槽zh-Hans的翻译错误
吐槽zh-Hans的翻译错误
好了就这样，半个月以后再来更一次（？

**Comment by ShingekiNoRex** [comment]
We have decided to merge `zh-CN` and `zh-Hans` into `zh`. Please check #566 for details and feel free to leave a review.

**Pull request closed without merging**
