### PR TITLE
Updated Russian localization

### PR DESCRIPTION
**Pull request by REALMWTH**
# SCP:SL Translation PR Template

## Language Name
Russian

## State Type of change (New language, changed existing Etc.)
Changed existing Russian language to relfect recent changes in English language.

# Checklist:
- [x] I have tested the translation changes ingame
- [x] I have made sure to not commit changes to multiple translations at the same time, or non-translation repo files
- [x] I have ran `EncodingNormalizer.exe` on my changed files before commiting 
   -  (Exception to this is when edits has __only__ been made in-browser. If this is the case, also check this box.)
- [x] I have made sure that I'm **not** submitting a duplicate translation 
- [x] I have made sure to **not** included any advertisements/pointers to non-game stuff other than the translation author in the credits file
- [x] I have made sure to label my translation folder by [Microsoft Language Tag Standards](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-lcid/a9eac961-e77d-41a6-90a5-ce1a8b0cdb9c)
   - Only in cases of **new** translations (Can be tested [Here](https://rextester.com/WDXPS97501)). Also check this box if the change is **not** a new translation

### CODE REVIEW

**Comment by REALMWTH** [comment]
@GuyFawkes76 please review ;)

**Comment by REALMWTH** [comment]
Btw, it seems that current version of SCP:SL (10.1.2) doesn't support coloring in Workstation screen
@MajorFox-MJ are you sure your changes will work in future update? Check screenshot below:
image

**Review by GuyFawkes76 — APPROVED** [review]

**Comment by REALMWTH** [comment]
I have fixed an issue within English language. Workstation.txt contained incorrect color tag, that led to the issue described above.

**Comment by Rnen** [comment]
> I have fixed an issue within English language. Workstation.txt contained incorrect color tag, that led to the issue described above.

Please keep changes in multiple languages separate. After all, you agreed to this in the PR
`"I have made sure to not commit changes to multiple translations at the same time, or non-translation repo files"`

**Comment by REALMWTH** [comment]
@Rnen just reverted fix and making a new PR

**Review by GuyFawkes76 — APPROVED** [review]

**Comment by REALMWTH** [comment]
@Rnen could you please merge this PR?

**Pull request merged**
