### PR TITLE
added french translation

### PR DESCRIPTION
**Pull request by Ganxly**
# SCP:SL Translation 

## Language
French translation

## Type of change
- [ ] New language addition
- [x] Changes to current existing language

## Have you tested the changes you've made?
- [x] Yes
- [ ] No

# Checklist:
- [x] I have made sure to not commit changes to other stuff than my own or the default english one
- [x] I have ran `EncodingNormalizer.exe` on my changed files before commiting
- [x] I have made sure that I'm not submitting a duplicate translation 
- [x] I have not included any advertisements/pointers to non-game stuff other than author in the folder name

### CODE REVIEW

**Comment by MichalPetryka** [comment]
Okay, stop, we want to have one translation per language, not four french translations

**Comment by Faeety** [comment]
Petris, he made that translation a long time ago, I reported it to Emperor and he didn't contacted him.
I reviewed one of his translation a time ago and it was great. It is different than the other @MichalPetryka .

**Comment by MichalPetryka** [comment]
Okay, i'm not saying that we should just close this, if we have one good translation, put that in game and remove other ones, and update that one translation over time

**Comment by Faeety** [comment]
Sure, only 1 translation 👍

**Comment by Rnen** [comment]
This has been declined due to beeing a duplicate submission.
Please make changes to the current existing translation, rather than adding another version.

**Comment by Ganxly** [comment]
What version i change ? The V.1 which is translated or the V.2 which isn't translated (by lucasbos45) ?

**Comment by Rnen** [comment]
The duplicate with the most issues has been removed, there is now only one French translation :ok_hand: :smile:

**Pull request closed without merging**
