### PR TITLE
Add Korean Translation

### PR DESCRIPTION
**Pull request by Dr-Devan**
It is used the official Korean wiki's expression

# SCP:SL Translation PR Template

## Language
Korean (한국어)

## Type of change
- [x] New language addition
- [ ] Changes to current existing language

## Have you tested the changes you've made?
- [x] Yes
- [ ] No

# Checklist:
- [x] I have made sure to not commit changes to other stuff than my own or the default english one
- [x] I have ran `EncodingNormalizer.exe` on my changed files before commiting
- [x] I have made sure that I'm not submitting a duplicate translation 
- [x] I have not included any advertisements/pointers to non-game stuff other than author in the folder name

### CODE REVIEW

**Comment by Rnen** [comment]
Unless this differs from the already added version of Korean
image
I cannot accept this Pull Request.

**Comment by Dr-Devan** [comment]
> Unless this differs from the already added version of Korean
> image
> I cannot accept this Pull Request.

Hello, Rnen.
Thanks to Reply.

Unfortunately, It appears Arizen have used my translation terms. I want to find my rights as a translator.
I've been translating SCP-SL for a long time,  all logs are archived following site:
http://sl.scp-wiki.kr/translate

Can you help me about it?

**Comment by liArizenil** [comment]
First, I apologize about this happening.

I talked to him just few seconds ago.

Seriously, I didnt know that there were another korean translation.

Anyway, after short talk, he want to remove the korean translation that I added and replace it with his.

I dont have any idea what should i do now.

**Comment by Dr-Devan** [comment]
Thanks, Arizen.
I've pushed in a new translation request.

I hope Rnen handle it well.

**Comment by liArizenil** [comment]
pls contact me if you need.
Discord : Arizen#9102

**Comment by Rnen** [comment]
We're in the process of replacing the `"by (name)"` with a standalone credits file containing all languages and their contributors.
I'll see to this when we make this change.

Unless there are any flaws with the current Korean, we will just keep it and credit Dr-Devanin the planned credits file.

**Comment by Dr-Devan** [comment]
Thanks, Rnen.

However, There is some problem on current Korean. So I'd like to change it.

**Comment by Rnen** [comment]
I see
But sadly, your changes on this Pull Request would add a whole another Korean folder
Hence changes must be applied to the existing folder instead before creating a Pull Request :sweat: 

Sorry for the inconvenience

**Comment by Dr-Devan** [comment]
It's not a problem.

I've created a new Pull Request.

**Pull request closed without merging**
