### PR TITLE
Changing Korean Translation

### PR DESCRIPTION
**Pull request by Dr-Devan**
- Fixed mistranslations
- Encoding Problem Fixed(not Perfect)

# SCP:SL Translation PR Template

## Language
Korean (한국어)

## Type of change
- [ ] New language addition
- [x] Changes to current existing language

## Have you tested the changes you've made?
- [x] Yes
- [ ] No

# Checklist:
- [x] I have made sure to not commit changes to other stuff than my own or the default english one
- [x] I have ran `EncodingNormalizer.exe` on my changed files before commiting
- [x] I have made sure that I'm not submitting a duplicate translation 
- [x] I have not included any advertisements/pointers to non-game stuff other than author in the folder name

### CODE REVIEW

**Comment by MichalPetryka** [comment]
Those are some huge changes, are you sure that everything is ok?

**Comment by liArizenil** [comment]
> Those are some huge changes, are you sure that everything is ok?

I'm pretty sure that this will be fine.
He worked on this for a long time. so his translation is better than mine. 
so I can understand it.

**Comment by Dr-Devan** [comment]
I cannot say that it is perfect. However, I've tried to use official terms and make to be more naturally.

Also, many of Korean users have been using my translation from the old times.

**Comment by SovietNakJi** [comment]
Are you ready to work? Dr-Devan

**Comment by SovietNakJi** [comment]
Now that you are ready, upload the Korea font!

**Comment by Rnen** [comment]
@Dr-Devan Right now, i added some new translation files to the english folder
[As can be seen here](https://github.com/northwood-studios/SCPSL-Translations/commit/75a55bf1865b84bc3d80ca26d3264b3cbed34d1e)

Tought i'd let you know just in case you wished to update the Korean to include theese.
I do not require any response to this, however if you do wish to add the new files, create a new Merge Request :smile:

**Pull request merged**
