### PR TITLE
Ko | Changes from 10.0.2

### PR DESCRIPTION
**Pull request by OneKoin**
# SCP:SL Translation PR Template

## Language Name
Korean

## State Type of change (New language, changed existing Etc.)
Unifed changes from 10.0.2

# Checklist:
- [x] I have tested the translation changes ingame
- [x] I have made sure to not commit changes to multiple translations at the same time, or non-translation repo files
- [x] I have ran `EncodingNormalizer.exe` on my changed files before commiting 
   -  (Exception to this is when edits has __only__ been made in-browser. If this is the case, also check this box.)
- [x] I have made sure that I'm **not** submitting a duplicate translation 
- [x] I have made sure to **not** included any advertisements/pointers to non-game stuff other than the translation author in the credits file
- [x] I have made sure to label my translation folder by [Microsoft Language Tag Standards](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-lcid/a9eac961-e77d-41a6-90a5-ce1a8b0cdb9c)
   - Only in cases of **new** translations (Can be tested [Here](https://rextester.com/WDXPS97501)). Also check this box if the change is **not** a new translation

**I wonder when will this be merged..**

### CODE REVIEW

**Review by Verrb — APPROVED** [review]
Nice quality.

**Comment by OneKoin** [comment]
It's been about 3 months.. the updates are not merged yet.. and the issue with fonts are not being fixed...
Might be the perfect timing for quitting

**Comment by MichalPetryka** [comment]
We're working with unity devs on an issue preventing us from fixing this

**Comment by OneKoin** [comment]
not only that, translation updates are not merged since last 2-3 month while other translations like poland are still merged by those who are in charge of specific language. Yeah I know it's hard to check if the translation is correct or wrong cause there's no one who can check this, but then, you should have used freelance translator at least

**Comment by OneKoin** [comment]
as your biggest competitor(which might be, or not) 'SCP: Recontainment' will be release in 2020, you, I mean Northwood, should care about those issues as soon as possible

**Comment by Rnen** [comment]
## Greetings!

Firstly i apologise for the delay of handling your previous PR, but like you said it, handling a foreign language nobody in the studio speaks is a delicate issue and requires extra studio resources. 
Also from looking at the previous PR, it seems it was very frequently updated. When pushing changes to a PR frequently, make sure to state that you're finished changing it, as we do not want to merge something that you are actively woking on.

> It's been about 3 months.. the updates are not merged yet.. and the issue with fonts are not being fixed...

Like mentioned by Petris earlier, the font issue is a colaborative effort between Northwood and the Unity devs.
The root cause of the issue is somewhat unclear and requires significant effort to resolve, hence why it's taking time.


> I mean Northwood, should care about those issues as soon as possible..
> +) those anti cheats too

We are constantly working on improving the game in every way possible. Each update features a ton of fixes that often don't even make it into the changelog. Like mentioned above, certain issues are more extensive and requires more work.

As for the anti-cheat, this is unrelated to translations. If you got any issues with this system not working as intented, feel free to submit a bug report or discuss the nature of the issue with our dedicated Tech Support team. Translators sadly can't do much about that.

---
### -Evan, Backend & Translation Manager

**Comment by OneKoin** [comment]
first of all thanks for replying even though you may think this of wining.

I've mentioned Anti-Cheat problem cause I wanted to say about the whole game. I don't know how SL is thought by users all around the world, but just in my country, its not that good. And I just wanted to warn that when several scp games' release are ahead.

And now this pr is ready, if there will be no more translation updates until 10.0.5 release, you may merge it as you check the changes.

**Comment by OneKoin** [comment]
Unable to update translation due to personal reason.

There will be no further Korean updates anymore.

**Comment by OneKoin** [comment]
Unable to update currently due to personal reason.

If there will be more translation update, do not merge this.
If not, this translation is reviewed by myself and completed.

**Comment by Dat-Joseph** [comment]
"f there will be more translation update, do not merge this." 
we cannot guarantee that. But will merge this now.

**Review by Dat-Joseph — APPROVED** [review]

**Pull request merged**
